{% set name = "pytest-check" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-check-{{ version }}.tar.gz
  sha256: 1c93bac3c45881a4aa5e1fcf6f0dccad9ee66df178de4ef90376be28fc249a10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.8
  run:
    - colorama >=0.4.6
    - pytest
    - python >=3.8

test:
  imports:
    - pytest_check
  requires:
    - pip
  source_files:
    - tests/
    - examples/
    - tox.ini
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/okken/pytest-check
  summary: A pytest plugin that allows multiple failures per test.
  license: MIT
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - thewchan
    - bskinn
    - anjos
