{% set name = "pytest_check" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_check-{{ version }}.tar.gz
  sha256: b9c8db6b1dee3c1e66162bd079b81c083296cb7131e9841519c28a40818a4875

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=2,<3
    - pip
    - python >=3.6
  run:
    - pytest >=6.0.0
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - pytest_check
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/okken/pytest-check
  summary: A pytest plugin that allows multiple failures per test.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
